### ISSUE TITLE
Valid 'mctype': 'snow' or 'doMC'

### ISSUE THREAD

**Issue by XiaofeiSunUCSF** [aertslab/AUCell#10] opened 2020-07-23 18:24 UTC
Hi,
Thank you for this wonderful package. 
I got one error while running the code, could you please help me figure it out?

Error in .AUCell_calcAUC(geneSets = geneSets, rankings = rankings, nCores = nCores,  : 
  Valid 'mctype': 'snow' or 'doMC'

**Comment by fchen365** [comment] 2020-09-07 21:53
I posted the same error in #12

**Comment by wzcaltech** [comment] 2020-11-25 09:10
same here, I use to be able to run SCENIC earlier this year (April-May) and didn't encounter this issue. Now I see the same error as described above.

**Comment by s-aibar** [comment] 2020-11-26 16:39
Hello,

Sorry, that was a bug that was introduced in one of the previous releases from AUCell. It should now be corrected, but you might still have that version. 

To solve it, just install the new version: 
```
BiocManager::install("AUCell")
packageVersion("AUCell")
```

If it installs a version older than 1.12 (might be determined by Bioconductor based on your R version), then you can try installing the latest version directly from Github: `devtools::install_github("aertslab/AUCell")`


Then the error should be fixed:
```
set.seed(123)
exprMatrix <- matrix(data=sample(c(rep(0, 5000), sample(1:3, 5000, replace=TRUE))),
                     nrow=20, 
                     dimnames=list(paste("Gene", 1:20, sep=""), 
                                   paste("Cell", 1:500, sep="")))
cells_rankings <- AUCell_buildRankings(exprMatrix, nCores=2)

fewGenes <- sample(rownames(exprMatrix), 10)
cells_AUC <- AUCell_calcAUC(fewGenes, cells_rankings, aucMaxRank=5, nCores=2)
```

Sorry for the inconvenience!

**Comment by Lix1993** [comment] 2020-12-24 05:43
save error with aucell 1.12.0

conda list |grep aucell
bioconductor-aucell       1.12.0                    r40_0    bioconda

**Comment by liuyifang** [comment] 2021-01-10 16:55
AUCell 1.12.0 on Bioconductor not work
AUCell 1.13.0 install from GitHub works

**Comment by Florian411** [comment] 2021-01-25 06:03
I can confirm that it only works with the AUCell 1.13 from GitHub.

**Comment by rsggsr** [comment] 2021-02-03 17:29
Double confirm again, only AUCell 1.13.0 installed from Github works.

**Comment by mfalchetti** [comment] 2021-02-17 21:48
AUCell 1.13.1 installed from GItHub still works

**Comment by allakarpova** [comment] 2021-02-19 02:23
AUCell 1.13.1 installed from GItHub didn't work for me

**Closed** 2021-02-19 21:14 UTC
Labels: Solved?

**Comment by martin-jeremy** [comment] 2021-05-05 14:01
AUCell 1.13.3 from GitHub didn't work ...

**Comment by dxw5099** [comment] 2021-06-04 07:55
Confirmed AUCell 1.13.3 from GitHub didn't work ...

**Comment by dxw5099** [comment] 2021-06-04 08:15
AUCell 1.13.3 from GitHub works for me after restarting R

> AUCell 1.13.3 from GitHub didn't work ...

**Comment by xf78** [comment] 2021-06-17 01:28
hi @Florian411 ,where can I download AUCell 1.13.0,i can not find AUCell 1.13.0 in https://github.com/aertslab/AUCell,thanks
